In [ ]:
import re
import nltk
import string
from nltk.stem import WordNetLemmatizer 

lemmatizer = WordNetLemmatizer() 

nltk_words = set(nltk.corpus.stopwords.words('english'))
stop_words = []
for word in nltk_words:
    stop_words.append(word.translate(str.maketrans('', '', string.punctuation)))

def preprocess(sentence):
    res = sentence.lower()
    res = res.translate(str.maketrans('', '', string.punctuation))
    tokenized_words = nltk.word_tokenize(res)
    res = [word for word in tokenized_words if word not in stop_words]
    res = [lemmatizer.lemmatize(r) for r in res]
    res = [re.sub(r"[^A-Za-z]+", '', r) for r in res]
    res = [r for r in res if len(r) > 3]
    return res

In [ ]:
import pandas as pd
df = pd.read_csv('res_mul_all.csv')


text_data = []
for sentence in df['review']:
    tokens = preprocess(sentence)
    text_data.append(tokens)

In [ ]:
f = open("data/restaurant.txt", "w", encoding='utf-8')
# f.write("texts\n")
for i in df['review']:
#     f.write(i + ".\n")
    
    text = preprocess(i)
    if text != '':
        f.write(' '.join(text).strip() + "\n")
    else:
        print('d')
f.close()

In [ ]:
preprocess("But the staff was so horrible to us.")

In [2]:
import spacy
from tqdm import tqdm_notebook as progress
nlp = spacy.load("en_core_web_sm")
k = ["But the staff was so horrible to us."]

In [ ]:
for a, i in progress(enumerate(k)):
    print(a, i)

In [39]:
from spacy.attrs import LOWER, POS, ENT_TYPE, IS_ALPHA
doc = nlp("ii ioi iii i")
# All strings mapped to integers, for easy export to numpy
np_array = doc.to_array([LOWER]).astype("int32")

In [40]:
np_array

array([-1482146813,   -98643383, -2088351250,  1893670687])

In [24]:
import numpy as np
k = np.array([[1, 2, 3], [4, 5, 6], [1, 7, 8]], np.int32)

In [26]:
print(k)
print(type(k))

[[1 2 3]
 [4 5 6]
 [1 7 8]]
<class 'numpy.ndarray'>


In [49]:
type(hash('iio' * 66))

int

In [47]:
hash('ioi' * 66)

8225943310644608043

In [65]:
def hash_sentence(sentence):
    words = sentence.split(" ")
    arr = []
    for word in words:
        arr.append([hash(word), 0, 0])
    return np.array(arr, np.int64)

In [68]:
z = hash_sentence("pasta penne pretty extra buttery creamy mean task diggest tasty first would full slice pizza count pennegot little moody afterwards cause stuffedlol")

In [69]:
print(z)
print(type(z))

[[ 2346524577764696749                    0                    0]
 [-1183346272160194109                    0                    0]
 [-4843004564945299839                    0                    0]
 [ -409697350746842008                    0                    0]
 [ 6386974108794674060                    0                    0]
 [ 2404885976424683889                    0                    0]
 [ 1389449383996616538                    0                    0]
 [ 3695770522569088556                    0                    0]
 [  367746513343387220                    0                    0]
 [-4600657434449866285                    0                    0]
 [ 2524548216594621186                    0                    0]
 [-6920592941390553853                    0                    0]
 [ 2189974010267561241                    0                    0]
 [-7489315867223030589                    0                    0]
 [-1541470353730966170                    0                    0]
 [-4044429

In [78]:
r = np.random.RandomState(42)
r.rand(4,5)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [81]:
r = np.random.RandomState(1234)
r.rand((4,5))

TypeError: 'tuple' object cannot be interpreted as an integer